'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { modeLabel, topicLabel } from '../lib/display-labels';

type TextResource={id:string;title:string;content:string;source_file:string;verbatim_confidence:string};
type Question={id:string;position:number;section:'CL'|'RL';topic:string;question:string;options:Record<string,string>;text_resources?:TextResource[];stimulus_assets?:string[];option_assets?:Record<string,string>;visual_resources?:{type:string;asset:string;placement:string}[];exam_id:string;source_file:string};
type Exam={id:string;mode:string;durationSeconds:number;sources:string[];questions:Question[]};
type Metric={questions:number;correct:number;incorrect:number;omitted:number;percentage:number};
type Result={mode:string;elapsedSeconds:number;totals:Metric;sections:{CL:Metric;RL:Metric};standardizedScoring:{reason:string};historySaved:boolean};
type Attempt={id:string;submittedAt:string;elapsedSeconds:number;timedOut:boolean;totalCorrect:number;percentage:number;clCorrect:number;rlCorrect:number};
type Insight={topic:string;label:string;section:'CL'|'RL';total:number;correct:number;accuracy:number;historicalQuestionsAvailable:number;rank?:number;recommendation?:string};
type Recommendations={attemptsAnalyzed:number;questionsAnalyzed:number;overallAccuracy:number;priorities:Insight[];strengths:Insight[];methodology:string};
type Catalog={bank:{total:number;eligible:number;sources:number};historicalExams:{id:string;label:string;total:number;cl:number;rl:number;ready:boolean}[];topics:{value:string;label:string;sections:string[];count:number}[]};
const formatTime=(seconds:number)=>[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(x=>String(x).padStart(2,'0')).join(':');
const deviceId=()=>{const key='umbral-udea-learner';let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID();localStorage.setItem(key,value)}return value};

export default function Home(){
 const[view,setView]=useState<'home'|'exam'|'result'|'history'|'recommendations'|'privacy'>('home');const[catalog,setCatalog]=useState<Catalog|null>(null);const[exam,setExam]=useState<Exam|null>(null);const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<Record<string,string>>({});const[remaining,setRemaining]=useState(10800);const[result,setResult]=useState<Result|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[history,setHistory]=useState<Attempt[]>([]);const[recs,setRecs]=useState<Recommendations|null>(null);const[practiceSection,setPracticeSection]=useState('CL');const[practiceTopic,setPracticeTopic]=useState('');const[practiceCount,setPracticeCount]=useState(10);const[historical,setHistorical]=useState('');
 const submittingRef=useRef(false);
 useEffect(()=>{fetch('/api/catalog').then(r=>r.json() as Promise<Catalog>).then(setCatalog).catch(()=>setError('No fue posible cargar el catálogo.'))},[]);
 async function start(mode='full'){setLoading(true);setError('');const params=new URLSearchParams({mode,learnerId:deviceId()});if(mode==='practice'){params.set('section',practiceSection);if(practiceTopic)params.set('topic',practiceTopic);params.set('count',String(practiceCount))}if(mode==='historical')params.set('source',historical);try{const response=await fetch(`/api/exam?${params}`);const data=await response.json() as Exam&{error?:string};if(!response.ok)throw new Error(data.error);setExam(data);setRemaining(data.durationSeconds);setAnswers({});setIndex(0);setView('exam')}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar.')}finally{setLoading(false)}}
 const submit=useCallback(async(timedOut=false,submittedAnswers=answers)=>{if(!exam||submittingRef.current)return;submittingRef.current=true;setLoading(true);setError('');try{const response=await fetch('/api/exam',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({simulationId:exam.id,learnerId:deviceId(),answers:submittedAnswers,elapsedSeconds:exam.durationSeconds-remaining,timedOut})});const data=await response.json() as Result&{error?:string};if(response.ok){setResult(data);setView('result')}else setError(data.error||'No se pudo entregar.')}catch{setError('No se pudo entregar. Revisa tu conexión e inténtalo de nuevo.')}finally{submittingRef.current=false;setLoading(false)}},[exam,answers,remaining]);
 function answerQuestion(questionId:string,letter:string){if(!exam||loading)return;const wasUnanswered=!answers[questionId];const nextAnswers={...answers,[questionId]:letter};setAnswers(nextAnswers);if(wasUnanswered&&Object.keys(nextAnswers).length===exam.questions.length)void submit(false,nextAnswers)}
 useEffect(()=>{if(view!=='exam')return;const timer=setInterval(()=>setRemaining(v=>{if(v<=1){clearInterval(timer);queueMicrotask(()=>submit(true));return 0}return v-1}),1000);return()=>clearInterval(timer)},[view,submit]);
 async function openHistory(){setLoading(true);const response=await fetch(`/api/history?learnerId=${deviceId()}`);const data=await response.json() as {attempts?:Attempt[]};setHistory(data.attempts||[]);setView('history');setLoading(false)}
 async function openRecs(){setLoading(true);const response=await fetch(`/api/recommendations?learnerId=${deviceId()}`);setRecs(await response.json() as Recommendations);setView('recommendations');setLoading(false)}
 async function clearProgress(){if(!window.confirm('¿Borrar definitivamente tus intentos y recomendaciones de este navegador?'))return;setLoading(true);setError('');try{const learnerId=deviceId();const response=await fetch(`/api/history?learnerId=${learnerId}`,{method:'DELETE'});if(!response.ok)throw new Error('No fue posible borrar el progreso.');localStorage.removeItem('umbral-udea-learner');setHistory([]);setRecs(null);setView('home');setError('Tu progreso fue eliminado correctamente.')}catch(e){setError(e instanceof Error?e.message:'No fue posible borrar el progreso.')}finally{setLoading(false)}}
 if(view==='exam'&&exam){const q=exam.questions[index],cl=exam.questions.map((x,i)=>({x,i})).filter(v=>v.x.section==='CL'),rl=exam.questions.map((x,i)=>({x,i})).filter(v=>v.x.section==='RL');const optionVisual=(letter:string)=>q.option_assets?.[letter]??q.visual_resources?.find(v=>v.placement===`option_${letter}`)?.asset;return <main className="examShell"><header className="examHeader"><div className="brand"><span className="brandMark">U</span><span>Umbral UdeA</span></div><div className="timer">{formatTime(remaining)}</div><button className="submit" onClick={()=>submit()} disabled={loading}>{loading?'Entregando…':'Entregar'}</button></header><aside className="navigator"><div className="navTitle"><span>{modeLabel(exam.mode)}</span><strong>{Object.keys(answers).length}/{exam.questions.length}</strong></div>{[['Competencia Lectora',cl],['Razonamiento Lógico',rl]].map(([label,items])=><div key={String(label)}><div className="sectionTag">{String(label)}</div><div className="questionGrid">{(items as {x:Question;i:number}[]).map(({x,i})=><button key={x.id} className={`${i===index?'active ':''}${answers[x.id]?'done':''}`} onClick={()=>setIndex(i)}>{i+1}</button>)}</div></div>)}</aside><section className="questionPanel">{error&&<p className="errorText" role="alert">{error}</p>}<div className="questionMeta"><span>{q.section}</span><span>{topicLabel(q.topic)}</span><span>{q.exam_id.replaceAll('_',' ')}</span></div><div className="questionNumber">Pregunta {index+1} de {exam.questions.length}</div>{q.text_resources?.map(resource=><details className="readingResource" key={resource.id} open><summary>{resource.title}</summary><div className="readingText">{resource.content}</div></details>)}{q.visual_resources?.filter(v=>v.placement==='stimulus').map(v=><img className="stimulus" key={v.asset} src={'/'+v.asset} alt="Estímulo visual original"/>)}<h2>{q.question}</h2>{q.visual_resources?.filter(v=>v.placement==='question').map(v=><img className="stimulus" key={v.asset} src={'/'+v.asset} alt="Recurso visual original"/>)}<div className="options">{Object.entries(q.options).map(([letter,text])=>{const asset=optionVisual(letter);return <button key={letter} className={answers[q.id]===letter?'selected':''} onClick={()=>answerQuestion(q.id,letter)} disabled={loading}><b>{letter}</b><span>{text}</span>{asset&&<img src={'/'+asset} alt={`Opción ${letter}`}/>}</button>})}</div><div className="questionActions"><button onClick={()=>setIndex(Math.max(0,index-1))} disabled={!index||loading}>← Anterior</button><button className="next" onClick={()=>setIndex(Math.min(exam.questions.length-1,index+1))} disabled={index===exam.questions.length-1||loading}>Siguiente →</button></div></section></main>}
 if(view==='result'&&result)return <main className="resultShell"><Top onBack={()=>setView('home')}/><section className="resultHero"><div className="eyebrow">RESULTADO · {modeLabel(result.mode).toUpperCase()}</div><h1>{result.totals.correct}<small>/ {result.totals.questions}</small></h1><p>{result.totals.percentage}% · {formatTime(result.elapsedSeconds)}</p></section><section className="resultCards"><MetricCard title="Competencia Lectora" metric={result.sections.CL}/><MetricCard title="Razonamiento Lógico" metric={result.sections.RL}/><div className="scoreNotice"><strong>Puntaje estandarizado</strong><span>No disponible</span><p>{result.standardizedScoring.reason}</p></div></section><div className="resultActions"><button className="primary" onClick={openRecs}>Ver plan recomendado →</button><button className="linkButton" onClick={openHistory}>Mi evolución</button></div></main>;
 if(view==='history')return <History attempts={history} onBack={()=>setView('home')} onRecs={openRecs}/>;
 if(view==='recommendations')return <RecommendationsView data={recs} onBack={openHistory} onStart={()=>start('full')}/>;
 if(view==='privacy')return <Privacy onBack={()=>setView('home')} onDelete={clearProgress} loading={loading}/>;
 return <main className="modeShell"><Top/><section className="modeHero"><div className="eyebrow">SIMULADOR Y ANALIZADOR UDEA</div><h1>Elige cómo<br/>vas a entrenar.</h1><p>Banco auditable de {catalog?.bank.total||474} preguntas; {catalog?.bank.eligible||437} verificadas de {catalog?.bank.sources||6} exámenes con clave.</p>{error&&<p className="errorText">{error}</p>}</section><section className="modeGrid"><article><span>01 · OFICIAL</span><h2>Simulacro completo</h2><p>80 preguntas combinadas de varios exámenes históricos: 40 CL + 40 RL, 180 minutos y antirrepetición.</p><button className="primary" onClick={()=>start('full')} disabled={loading}>Comenzar →</button></article><article><span>02 · FIDELIDAD</span><h2>Recrear histórico</h2><p>Solo se habilita cuando las 80 preguntas del examen específico están verificadas.</p><select value={historical} onChange={e=>setHistorical(e.target.value)}><option value="">Selecciona un examen</option>{catalog?.historicalExams.map(x=><option key={x.id} value={x.id} disabled={!x.ready}>{x.label} · {x.total}/80 verificadas</option>)}</select><button className="secondary" onClick={()=>start('historical')} disabled={!historical||loading}>Recrear examen</button></article><article><span>03 · ENFOQUE</span><h2>Práctica personalizada</h2><div className="practiceForm"><select value={practiceSection} onChange={e=>setPracticeSection(e.target.value)}><option value="CL">Competencia Lectora</option><option value="RL">Razonamiento Lógico</option></select><select value={practiceTopic} onChange={e=>setPracticeTopic(e.target.value)}><option value="">Todos los temas</option>{catalog?.topics.filter(x=>x.sections.includes(practiceSection)).map(x=><option key={x.value} value={x.value}>{x.label} ({x.count})</option>)}</select><input aria-label="Cantidad de preguntas" type="number" min="5" max="40" value={practiceCount} onChange={e=>setPracticeCount(Number(e.target.value))}/></div><button className="secondary" onClick={()=>start('practice')} disabled={loading}>Iniciar práctica</button></article></section><footer className="modeFooter"><button onClick={openHistory}>Mi progreso</button><button onClick={()=>setView('privacy')}>Privacidad</button><span>Proyecto educativo independiente; no es un sitio oficial de la Universidad de Antioquia.</span></footer></main>
}
function Top({onBack}:{onBack?:()=>void}){return <header className="topbar"><div className="brand"><span className="brandMark">U</span><span>Umbral UdeA</span></div>{onBack&&<button className="linkButton" onClick={onBack}>Volver al inicio</button>}</header>}
function MetricCard({title,metric}:{title:string;metric:Metric}){return <article className="metricCard"><span>{title}</span><strong>{metric.correct}<small>/{metric.questions}</small></strong><div><i style={{width:`${metric.percentage}%`}}/></div><p>{metric.percentage}% · {metric.omitted} omitidas</p></article>}
function History({attempts,onBack,onRecs}:{attempts:Attempt[];onBack:()=>void;onRecs:()=>void}){return <main className="historyShell"><Top onBack={onBack}/><section className="historyHero"><div><div className="eyebrow">EVOLUCIÓN</div><h1>Tu progreso,<br/>intento a intento.</h1></div><button className="primary" onClick={onRecs}>Ver recomendaciones →</button></section>{!attempts.length?<div className="emptyHistory"><h2>Aún no hay intentos.</h2></div>:<section className="attemptList">{attempts.map((x,i)=><article key={x.id}><div className="attemptOrder">#{attempts.length-i}</div><div><strong>{new Date(x.submittedAt).toLocaleString('es-CO')}</strong><span>{formatTime(x.elapsedSeconds)}</span></div><div className="sectionScores"><span>CL <b>{x.clCorrect}</b></span><span>RL <b>{x.rlCorrect}</b></span></div><div className="attemptTotal"><strong>{x.totalCorrect}</strong></div></article>)}</section>}</main>}
function Privacy({onBack,onDelete,loading}:{onBack:()=>void;onDelete:()=>void;loading:boolean}){return <main className="historyShell"><Top onBack={onBack}/><section className="historyHero"><div><div className="eyebrow">PRIVACIDAD</div><h1>Tu práctica,<br/>bajo tu control.</h1></div></section><section className="emptyHistory"><h2>Datos que conserva Umbral UdeA</h2><p>El sistema crea un identificador aleatorio en este navegador para guardar tus intentos, resultados y recomendaciones. No solicita nombre, correo electrónico, documento ni ubicación.</p><p>Los datos se usan únicamente para mostrar tu progreso y evitar repeticiones. Si cambias de navegador o dispositivo, el historial no se transfiere.</p><div className="resultActions"><button className="secondary" onClick={onDelete} disabled={loading}>{loading?'Borrando…':'Borrar mi progreso'}</button></div></section></main>}
function RecommendationsView({data,onBack,onStart}:{data:Recommendations|null;onBack:()=>void;onStart:()=>void}){return <main className="recommendShell"><Top onBack={onBack}/><section className="recommendHero"><div className="eyebrow">ENTRENAMIENTO PERSONALIZADO</div><h1>Tu próxima sesión,<br/>con propósito.</h1></section>{!data?.attemptsAnalyzed?<div className="emptyHistory"><h2>Completa primero un simulacro.</h2></div>:<><section className="recommendSummary"><div><span>Intentos</span><strong>{data.attemptsAnalyzed}</strong></div><div><span>Preguntas</span><strong>{data.questionsAnalyzed}</strong></div><div><span>Precisión</span><strong>{data.overallAccuracy}%</strong></div></section><div className="priorityGrid">{data.priorities.map(x=><article key={x.topic}><div className="priorityTop"><span>PRIORIDAD {x.rank}</span><b>{x.section}</b></div><h3>{x.label}</h3><div className="accuracy"><strong>{x.accuracy}%</strong></div><p>{x.recommendation}</p></article>)}</div><div className="planAction"><button className="primary" onClick={onStart}>Simulacro completo →</button></div></>}</main>}
